name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */2 * *'  # Run at midnight every 2 days
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET 'https://${{ secrets.SUPABASE_PROJECT_ID }}.supabase.co/rest/v1/' \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" 